ALTER TABLE public.white_label_configs
  ADD COLUMN IF NOT EXISTS secondary_color text,
  ADD COLUMN IF NOT EXISTS sidebar_background text,
  ADD COLUMN IF NOT EXISTS sidebar_foreground text,
  ADD COLUMN IF NOT EXISTS sidebar_accent text,
  ADD COLUMN IF NOT EXISTS dashboard_background text,
  ADD COLUMN IF NOT EXISTS dashboard_accent text,
  ADD COLUMN IF NOT EXISTS font_family_sans text,
  ADD COLUMN IF NOT EXISTS font_family_heading text,
  ADD COLUMN IF NOT EXISTS font_family_mono text,
  ADD COLUMN IF NOT EXISTS font_size_base text,
  ADD COLUMN IF NOT EXISTS default_color_mode text CHECK (default_color_mode IN ('light','dark','system')) DEFAULT 'system',
  ADD COLUMN IF NOT EXISTS dark_primary_color text,
  ADD COLUMN IF NOT EXISTS dark_background_color text,
  ADD COLUMN IF NOT EXISTS dark_accent_color text,
  ADD COLUMN IF NOT EXISTS login_background_url text,
  ADD COLUMN IF NOT EXISTS login_headline text,
  ADD COLUMN IF NOT EXISTS login_subheadline text,
  ADD COLUMN IF NOT EXISTS login_layout text CHECK (login_layout IN ('centered','split','minimal')) DEFAULT 'centered',
  ADD COLUMN IF NOT EXISTS loader_url text,
  ADD COLUMN IF NOT EXISTS loader_style text CHECK (loader_style IN ('spinner','dots','bar','logo','custom')) DEFAULT 'spinner',
  ADD COLUMN IF NOT EXISTS icon_style text CHECK (icon_style IN ('outline','solid','duotone')) DEFAULT 'outline',
  ADD COLUMN IF NOT EXISTS icon_stroke_width numeric DEFAULT 2,
  ADD COLUMN IF NOT EXISTS border_radius text,
  ADD COLUMN IF NOT EXISTS custom_js text,
  ADD COLUMN IF NOT EXISTS email_logo_url text,
  ADD COLUMN IF NOT EXISTS email_from_name text,
  ADD COLUMN IF NOT EXISTS email_primary_color text,
  ADD COLUMN IF NOT EXISTS email_header_color text,
  ADD COLUMN IF NOT EXISTS custom_domain_verified boolean DEFAULT false;