
ALTER TABLE public.plans
  ADD COLUMN IF NOT EXISTS tier public.plan_tier NOT NULL DEFAULT 'custom',
  ADD COLUMN IF NOT EXISTS trial_days integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS is_public boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS is_custom boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS badge text,
  ADD COLUMN IF NOT EXISTS tagline text,
  ADD COLUMN IF NOT EXISTS cta_label text,
  ADD COLUMN IF NOT EXISTS highlight boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS monthly_plan_code text;

CREATE INDEX IF NOT EXISTS idx_plans_tier_interval
  ON public.plans (tier, interval)
  WHERE is_active;

-- 2. Preserve original plan-management RLS policy.
DROP POLICY IF EXISTS "Super admins manage plans" ON public.plans;
CREATE POLICY "Super admins manage plans" ON public.plans
  FOR ALL TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.user_roles ur
      WHERE ur.user_id = auth.uid()
        AND ur.role IN ('superadmin','support')
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.user_roles ur
      WHERE ur.user_id = auth.uid()
        AND ur.role = 'superadmin'
    )
  );

-- 3. Retire the legacy Pro SKU without deleting history/FK references.
UPDATE public.plans
SET is_active=false, is_public=false, highlight=false, badge='Legacy', sort_order=900
WHERE code IN ('pro','pro_yearly');

-- 4. Canonical catalog.
-- Every SKU repeats full JSON intentionally so each can be edited in isolation.

-- ═════════════════════════ FREE ═════════════════════════

-- free | month | $0.00
INSERT INTO public.plans (
  code, name, tier, description, tagline, badge, cta_label,
  price_cents, currency, interval, trial_days, features, limits,
  sort_order, is_active, is_public, is_custom, highlight, monthly_plan_code
)
VALUES (
  'free',
  'Miễn phí',
  'free',
  'Gói miễn phí lâu dài dành cho người kinh doanh độc lập, hộ kinh doanh và đội nhóm nhỏ đang tìm hiểu nền tảng. Tổ chức dữ liệu khách hàng, quản lý các hội thoại thiết yếu và thử nghiệm quy trình CRM cốt lõi với hạn mức phù hợp trước khi chuyển sang gói trả phí.',
  'Khám phá CRM, hộp thư và không gian quản lý khách hàng cốt lõi hoàn toàn miễn phí.',
  NULL,
  'Bắt đầu miễn phí',
  0,
  'USD',
  'month',
  0,
  $features_1$
{
  "ai.reply_assistant": false,
  "ai.knowledge_base": false,
  "automations.enabled": false,
  "marketing.ab_testing": false,
  "marketing.drip_sequences": false,
  "bi.custom_dashboards": false,
  "bi.scheduled_reports": false,
  "api.public_access": false,
  "security.sso": false,
  "security.audit_export": false,
  "inbox": true,
  "broadcasts": false,
  "templates": true,
  "automations": false,
  "chatbot": false,
  "ai": false,
  "crm": true,
  "commerce": false,
  "analytics": false,
  "api": false,
  "white_label": false,
  "sso": false,
  "audit_export": false,
  "sla": false,
  "support": "community",
  "channels": 1
}
$features_1$::jsonb,
  $limits_1$
{
  "seats": 2,
  "organizations": 1,
  "workspaces": 1,
  "contacts": 500,
  "companies": 100,
  "deals": 50,
  "pipelines": 1,
  "campaigns_per_month": 1,
  "broadcasts_per_month": 100,
  "templates": 5,
  "workflows": 2,
  "ai_requests_per_month": 50,
  "storage_mb": 250,
  "api_requests_per_month": 1000,
  "phone_numbers": 1,
  "whatsapp_accounts": 1,
  "custom_fields": 5,
  "reports": 3,
  "exports_per_month": 5,
  "messages_per_month": 500,
  "agents": 1,
  "storage_gb": 0.25
}
$limits_1$::jsonb,
  10,
  true,
  true,
  false,
  false,
  NULL
)
ON CONFLICT (code) DO UPDATE SET
  name=EXCLUDED.name,
  tier=EXCLUDED.tier,
  description=EXCLUDED.description,
  tagline=EXCLUDED.tagline,
  badge=EXCLUDED.badge,
  cta_label=EXCLUDED.cta_label,
  price_cents=EXCLUDED.price_cents,
  currency=EXCLUDED.currency,
  interval=EXCLUDED.interval,
  trial_days=EXCLUDED.trial_days,
  features=EXCLUDED.features,
  limits=EXCLUDED.limits,
  sort_order=EXCLUDED.sort_order,
  is_active=EXCLUDED.is_active,
  is_public=EXCLUDED.is_public,
  is_custom=EXCLUDED.is_custom,
  highlight=EXCLUDED.highlight,
  monthly_plan_code=EXCLUDED.monthly_plan_code;

-- free_yearly | year | $0.00
INSERT INTO public.plans (
  code, name, tier, description, tagline, badge, cta_label,
  price_cents, currency, interval, trial_days, features, limits,
  sort_order, is_active, is_public, is_custom, highlight, monthly_plan_code
)
VALUES (
  'free_yearly',
  'Miễn phí (hằng năm)',
  'free',
  'Gói miễn phí lâu dài dành cho người kinh doanh độc lập, hộ kinh doanh và đội nhóm nhỏ đang tìm hiểu nền tảng. Tổ chức dữ liệu khách hàng, quản lý các hội thoại thiết yếu và thử nghiệm quy trình CRM cốt lõi với hạn mức phù hợp trước khi chuyển sang gói trả phí. Biến thể hằng năm này chỉ dùng cho quản trị và được ẩn khỏi bảng giá công khai vì gói Miễn phí không yêu cầu thanh toán theo năm.',
  'Không gian làm việc miễn phí, không có cam kết hằng năm.',
  NULL,
  'Bắt đầu miễn phí',
  0,
  'USD',
  'year',
  0,
  $features_2$
{
  "ai.reply_assistant": false,
  "ai.knowledge_base": false,
  "automations.enabled": false,
  "marketing.ab_testing": false,
  "marketing.drip_sequences": false,
  "bi.custom_dashboards": false,
  "bi.scheduled_reports": false,
  "api.public_access": false,
  "security.sso": false,
  "security.audit_export": false,
  "inbox": true,
  "broadcasts": false,
  "templates": true,
  "automations": false,
  "chatbot": false,
  "ai": false,
  "crm": true,
  "commerce": false,
  "analytics": false,
  "api": false,
  "white_label": false,
  "sso": false,
  "audit_export": false,
  "sla": false,
  "support": "community",
  "channels": 1
}
$features_2$::jsonb,
  $limits_2$
{
  "seats": 2,
  "organizations": 1,
  "workspaces": 1,
  "contacts": 500,
  "companies": 100,
  "deals": 50,
  "pipelines": 1,
  "campaigns_per_month": 1,
  "broadcasts_per_month": 100,
  "templates": 5,
  "workflows": 2,
  "ai_requests_per_month": 50,
  "storage_mb": 250,
  "api_requests_per_month": 1000,
  "phone_numbers": 1,
  "whatsapp_accounts": 1,
  "custom_fields": 5,
  "reports": 3,
  "exports_per_month": 5,
  "messages_per_month": 500,
  "agents": 1,
  "storage_gb": 0.25
}
$limits_2$::jsonb,
  11,
  false,
  false,
  false,
  false,
  'free'
)
ON CONFLICT (code) DO UPDATE SET
  name=EXCLUDED.name,
  tier=EXCLUDED.tier,
  description=EXCLUDED.description,
  tagline=EXCLUDED.tagline,
  badge=EXCLUDED.badge,
  cta_label=EXCLUDED.cta_label,
  price_cents=EXCLUDED.price_cents,
  currency=EXCLUDED.currency,
  interval=EXCLUDED.interval,
  trial_days=EXCLUDED.trial_days,
  features=EXCLUDED.features,
  limits=EXCLUDED.limits,
  sort_order=EXCLUDED.sort_order,
  is_active=EXCLUDED.is_active,
  is_public=EXCLUDED.is_public,
  is_custom=EXCLUDED.is_custom,
  highlight=EXCLUDED.highlight,
  monthly_plan_code=EXCLUDED.monthly_plan_code;

-- free_lifetime | lifetime | $0.00
INSERT INTO public.plans (
  code, name, tier, description, tagline, badge, cta_label,
  price_cents, currency, interval, trial_days, features, limits,
  sort_order, is_active, is_public, is_custom, highlight, monthly_plan_code
)
VALUES (
  'free_lifetime',
  'Miễn phí trọn đời',
  'free',
  'Gói miễn phí lâu dài dành cho người kinh doanh độc lập, hộ kinh doanh và đội nhóm nhỏ đang tìm hiểu nền tảng. Tổ chức dữ liệu khách hàng, quản lý các hội thoại thiết yếu và thử nghiệm quy trình CRM cốt lõi với hạn mức phù hợp trước khi chuyển sang gói trả phí. Biến thể tương thích này được ẩn và không dùng để bán.',
  'Biến thể tương thích riêng của gói miễn phí, không có đăng ký định kỳ.',
  NULL,
  'Bắt đầu miễn phí',
  0,
  'USD',
  'lifetime',
  0,
  $features_3$
{
  "ai.reply_assistant": false,
  "ai.knowledge_base": false,
  "automations.enabled": false,
  "marketing.ab_testing": false,
  "marketing.drip_sequences": false,
  "bi.custom_dashboards": false,
  "bi.scheduled_reports": false,
  "api.public_access": false,
  "security.sso": false,
  "security.audit_export": false,
  "inbox": true,
  "broadcasts": false,
  "templates": true,
  "automations": false,
  "chatbot": false,
  "ai": false,
  "crm": true,
  "commerce": false,
  "analytics": false,
  "api": false,
  "white_label": false,
  "sso": false,
  "audit_export": false,
  "sla": false,
  "support": "community",
  "channels": 1
}
$features_3$::jsonb,
  $limits_3$
{
  "seats": 2,
  "organizations": 1,
  "workspaces": 1,
  "contacts": 500,
  "companies": 100,
  "deals": 50,
  "pipelines": 1,
  "campaigns_per_month": 1,
  "broadcasts_per_month": 100,
  "templates": 5,
  "workflows": 2,
  "ai_requests_per_month": 50,
  "storage_mb": 250,
  "api_requests_per_month": 1000,
  "phone_numbers": 1,
  "whatsapp_accounts": 1,
  "custom_fields": 5,
  "reports": 3,
  "exports_per_month": 5,
  "messages_per_month": 500,
  "agents": 1,
  "storage_gb": 0.25
}
$limits_3$::jsonb,
  12,
  false,
  false,
  false,
  false,
  'free'
)
ON CONFLICT (code) DO UPDATE SET
  name=EXCLUDED.name,
  tier=EXCLUDED.tier,
  description=EXCLUDED.description,
  tagline=EXCLUDED.tagline,
  badge=EXCLUDED.badge,
  cta_label=EXCLUDED.cta_label,
  price_cents=EXCLUDED.price_cents,
  currency=EXCLUDED.currency,
  interval=EXCLUDED.interval,
  trial_days=EXCLUDED.trial_days,
  features=EXCLUDED.features,
  limits=EXCLUDED.limits,
  sort_order=EXCLUDED.sort_order,
  is_active=EXCLUDED.is_active,
  is_public=EXCLUDED.is_public,
  is_custom=EXCLUDED.is_custom,
  highlight=EXCLUDED.highlight,
  monthly_plan_code=EXCLUDED.monthly_plan_code;

-- ═════════════════════════ STARTER ═════════════════════════

-- starter | month | $9.00
INSERT INTO public.plans (
  code, name, tier, description, tagline, badge, cta_label,
  price_cents, currency, interval, trial_days, features, limits,
  sort_order, is_active, is_public, is_custom, highlight, monthly_plan_code
)
VALUES (
  'starter',
  'Khởi đầu',
  'starter',
  'Dành cho hộ kinh doanh, người kinh doanh độc lập và đội nhóm rất nhỏ cần CRM thực dụng cùng không gian làm việc đa kênh, không mang theo độ phức tạp của hệ thống doanh nghiệp lớn. Bao gồm hỗ trợ AI cơ bản, tự động hóa đơn giản, gửi tin hàng loạt và dung lượng đủ cho hoạt động khách hàng hằng ngày.',
  'Bắt đầu bán hàng và phục vụ khách hàng với không gian làm việc tinh gọn có AI hỗ trợ.',
  NULL,
  'Dùng thử miễn phí',
  900,
  'USD',
  'month',
  14,
  $features_4$
{
  "ai.reply_assistant": true,
  "ai.knowledge_base": false,
  "automations.enabled": true,
  "marketing.ab_testing": false,
  "marketing.drip_sequences": false,
  "bi.custom_dashboards": false,
  "bi.scheduled_reports": false,
  "api.public_access": false,
  "security.sso": false,
  "security.audit_export": false,
  "inbox": true,
  "broadcasts": true,
  "templates": true,
  "automations": true,
  "chatbot": false,
  "ai": true,
  "crm": true,
  "commerce": false,
  "analytics": false,
  "api": false,
  "white_label": false,
  "sso": false,
  "audit_export": false,
  "sla": false,
  "support": "community",
  "channels": 2
}
$features_4$::jsonb,
  $limits_4$
{
  "seats": 3,
  "organizations": 1,
  "workspaces": 2,
  "contacts": 3000,
  "companies": 500,
  "deals": 500,
  "pipelines": 2,
  "campaigns_per_month": 5,
  "broadcasts_per_month": 2500,
  "templates": 20,
  "workflows": 10,
  "ai_requests_per_month": 500,
  "storage_mb": 1024,
  "api_requests_per_month": 25000,
  "phone_numbers": 1,
  "whatsapp_accounts": 1,
  "custom_fields": 20,
  "reports": 10,
  "exports_per_month": 50,
  "messages_per_month": 2500,
  "agents": 2,
  "storage_gb": 1
}
$limits_4$::jsonb,
  20,
  true,
  true,
  false,
  false,
  NULL
)
ON CONFLICT (code) DO UPDATE SET
  name=EXCLUDED.name,
  tier=EXCLUDED.tier,
  description=EXCLUDED.description,
  tagline=EXCLUDED.tagline,
  badge=EXCLUDED.badge,
  cta_label=EXCLUDED.cta_label,
  price_cents=EXCLUDED.price_cents,
  currency=EXCLUDED.currency,
  interval=EXCLUDED.interval,
  trial_days=EXCLUDED.trial_days,
  features=EXCLUDED.features,
  limits=EXCLUDED.limits,
  sort_order=EXCLUDED.sort_order,
  is_active=EXCLUDED.is_active,
  is_public=EXCLUDED.is_public,
  is_custom=EXCLUDED.is_custom,
  highlight=EXCLUDED.highlight,
  monthly_plan_code=EXCLUDED.monthly_plan_code;

-- starter_yearly | year | $86.40
INSERT INTO public.plans (
  code, name, tier, description, tagline, badge, cta_label,
  price_cents, currency, interval, trial_days, features, limits,
  sort_order, is_active, is_public, is_custom, highlight, monthly_plan_code
)
VALUES (
  'starter_yearly',
  'Khởi đầu (hằng năm)',
  'starter',
  'Dành cho hộ kinh doanh, người kinh doanh độc lập và đội nhóm rất nhỏ cần CRM thực dụng cùng không gian làm việc đa kênh, không mang theo độ phức tạp của hệ thống doanh nghiệp lớn. Bao gồm hỗ trợ AI cơ bản, tự động hóa đơn giản, gửi tin hàng loạt và dung lượng đủ cho hoạt động khách hàng hằng ngày. Thanh toán hằng năm, tiết kiệm 20% so với trả theo tháng trong 12 tháng.',
  'Bắt đầu bán hàng và phục vụ khách hàng với không gian làm việc tinh gọn có AI hỗ trợ — thanh toán hằng năm và tiết kiệm 20%.',
  NULL,
  'Dùng thử miễn phí',
  8640,
  'USD',
  'year',
  14,
  $features_5$
{
  "ai.reply_assistant": true,
  "ai.knowledge_base": false,
  "automations.enabled": true,
  "marketing.ab_testing": false,
  "marketing.drip_sequences": false,
  "bi.custom_dashboards": false,
  "bi.scheduled_reports": false,
  "api.public_access": false,
  "security.sso": false,
  "security.audit_export": false,
  "inbox": true,
  "broadcasts": true,
  "templates": true,
  "automations": true,
  "chatbot": false,
  "ai": true,
  "crm": true,
  "commerce": false,
  "analytics": false,
  "api": false,
  "white_label": false,
  "sso": false,
  "audit_export": false,
  "sla": false,
  "support": "community",
  "channels": 2
}
$features_5$::jsonb,
  $limits_5$
{
  "seats": 3,
  "organizations": 1,
  "workspaces": 2,
  "contacts": 3000,
  "companies": 500,
  "deals": 500,
  "pipelines": 2,
  "campaigns_per_month": 5,
  "broadcasts_per_month": 2500,
  "templates": 20,
  "workflows": 10,
  "ai_requests_per_month": 500,
  "storage_mb": 1024,
  "api_requests_per_month": 25000,
  "phone_numbers": 1,
  "whatsapp_accounts": 1,
  "custom_fields": 20,
  "reports": 10,
  "exports_per_month": 50,
  "messages_per_month": 2500,
  "agents": 2,
  "storage_gb": 1
}
$limits_5$::jsonb,
  21,
  true,
  true,
  false,
  false,
  'starter'
)
ON CONFLICT (code) DO UPDATE SET
  name=EXCLUDED.name,
  tier=EXCLUDED.tier,
  description=EXCLUDED.description,
  tagline=EXCLUDED.tagline,
  badge=EXCLUDED.badge,
  cta_label=EXCLUDED.cta_label,
  price_cents=EXCLUDED.price_cents,
  currency=EXCLUDED.currency,
  interval=EXCLUDED.interval,
  trial_days=EXCLUDED.trial_days,
  features=EXCLUDED.features,
  limits=EXCLUDED.limits,
  sort_order=EXCLUDED.sort_order,
  is_active=EXCLUDED.is_active,
  is_public=EXCLUDED.is_public,
  is_custom=EXCLUDED.is_custom,
  highlight=EXCLUDED.highlight,
  monthly_plan_code=EXCLUDED.monthly_plan_code;

-- starter_lifetime | lifetime | $299.00
INSERT INTO public.plans (
  code, name, tier, description, tagline, badge, cta_label,
  price_cents, currency, interval, trial_days, features, limits,
  sort_order, is_active, is_public, is_custom, highlight, monthly_plan_code
)
VALUES (
  'starter_lifetime',
  'Khởi đầu trọn đời',
  'starter',
  'Dành cho hộ kinh doanh, người kinh doanh độc lập và đội nhóm rất nhỏ cần CRM thực dụng cùng không gian làm việc đa kênh, không mang theo độ phức tạp của hệ thống doanh nghiệp lớn. Bao gồm hỗ trợ AI cơ bản, tự động hóa đơn giản, gửi tin hàng loạt và dung lượng đủ cho hoạt động khách hàng hằng ngày. Đây là giấy phép nền tảng thanh toán một lần cho gói này. Hạn mức sử dụng vẫn theo quy định của gói; chi phí nhắn tin, AI, thoại, đám mây, thanh toán và nhà cung cấp bên thứ ba không được bao gồm trừ khi hợp đồng thương mại nêu rõ.',
  'Thanh toán một lần để sử dụng nền tảng lâu dài với hạn mức gói Khởi đầu.',
  'Ưu đãi riêng',
  'Liên hệ kinh doanh',
  29900,
  'USD',
  'lifetime',
  0,
  $features_6$
{
  "ai.reply_assistant": true,
  "ai.knowledge_base": false,
  "automations.enabled": true,
  "marketing.ab_testing": false,
  "marketing.drip_sequences": false,
  "bi.custom_dashboards": false,
  "bi.scheduled_reports": false,
  "api.public_access": false,
  "security.sso": false,
  "security.audit_export": false,
  "inbox": true,
  "broadcasts": true,
  "templates": true,
  "automations": true,
  "chatbot": false,
  "ai": true,
  "crm": true,
  "commerce": false,
  "analytics": false,
  "api": false,
  "white_label": false,
  "sso": false,
  "audit_export": false,
  "sla": false,
  "support": "community",
  "channels": 2
}
$features_6$::jsonb,
  $limits_6$
{
  "seats": 3,
  "organizations": 1,
  "workspaces": 2,
  "contacts": 3000,
  "companies": 500,
  "deals": 500,
  "pipelines": 2,
  "campaigns_per_month": 5,
  "broadcasts_per_month": 2500,
  "templates": 20,
  "workflows": 10,
  "ai_requests_per_month": 500,
  "storage_mb": 1024,
  "api_requests_per_month": 25000,
  "phone_numbers": 1,
  "whatsapp_accounts": 1,
  "custom_fields": 20,
  "reports": 10,
  "exports_per_month": 50,
  "messages_per_month": 2500,
  "agents": 2,
  "storage_gb": 1
}
$limits_6$::jsonb,
  22,
  true,
  false,
  false,
  false,
  'starter'
)
ON CONFLICT (code) DO UPDATE SET
  name=EXCLUDED.name,
  tier=EXCLUDED.tier,
  description=EXCLUDED.description,
  tagline=EXCLUDED.tagline,
  badge=EXCLUDED.badge,
  cta_label=EXCLUDED.cta_label,
  price_cents=EXCLUDED.price_cents,
  currency=EXCLUDED.currency,
  interval=EXCLUDED.interval,
  trial_days=EXCLUDED.trial_days,
  features=EXCLUDED.features,
  limits=EXCLUDED.limits,
  sort_order=EXCLUDED.sort_order,
  is_active=EXCLUDED.is_active,
  is_public=EXCLUDED.is_public,
  is_custom=EXCLUDED.is_custom,
  highlight=EXCLUDED.highlight,
  monthly_plan_code=EXCLUDED.monthly_plan_code;

-- ═════════════════════════ PROFESSIONAL ═════════════════════════

-- professional | month | $19.00
INSERT INTO public.plans (
  code, name, tier, description, tagline, badge, cta_label,
  price_cents, currency, interval, trial_days, features, limits,
  sort_order, is_active, is_public, is_custom, highlight, monthly_plan_code
)
VALUES (
  'professional',
  'Chuyên nghiệp',
  'professional',
  'Dành cho doanh nghiệp dịch vụ và đội ngũ bán hàng đang phát triển, cần nhiều hơn một CRM cơ bản. Bổ sung hỗ trợ và tri thức bằng AI, tự động hóa nhiều bước, thử nghiệm chiến dịch, trang tổng quan chuyên sâu và API công khai nhưng vẫn đủ đơn giản để đội ngũ tinh gọn vận hành hằng ngày.',
  'Vận hành đồng bộ khách hàng, bán hàng, marketing và tự động hóa cho đội ngũ đang phát triển.',
  'Phổ biến nhất',
  'Dùng thử miễn phí',
  1900,
  'USD',
  'month',
  14,
  $features_7$
{
  "ai.reply_assistant": true,
  "ai.knowledge_base": true,
  "automations.enabled": true,
  "marketing.ab_testing": true,
  "marketing.drip_sequences": true,
  "bi.custom_dashboards": true,
  "bi.scheduled_reports": false,
  "api.public_access": true,
  "security.sso": false,
  "security.audit_export": false,
  "inbox": true,
  "broadcasts": true,
  "templates": true,
  "automations": true,
  "chatbot": true,
  "ai": true,
  "crm": true,
  "commerce": true,
  "analytics": true,
  "api": true,
  "white_label": false,
  "sso": false,
  "audit_export": false,
  "sla": false,
  "support": "email",
  "channels": 3
}
$features_7$::jsonb,
  $limits_7$
{
  "seats": 7,
  "organizations": 1,
  "workspaces": 3,
  "contacts": 10000,
  "companies": 2000,
  "deals": 2000,
  "pipelines": 5,
  "campaigns_per_month": 15,
  "broadcasts_per_month": 10000,
  "templates": 50,
  "workflows": 30,
  "ai_requests_per_month": 10000,
  "storage_mb": 5120,
  "api_requests_per_month": 100000,
  "phone_numbers": 3,
  "whatsapp_accounts": 2,
  "custom_fields": 50,
  "reports": 25,
  "exports_per_month": 250,
  "messages_per_month": 10000,
  "agents": 5,
  "storage_gb": 5
}
$limits_7$::jsonb,
  30,
  true,
  true,
  false,
  true,
  NULL
)
ON CONFLICT (code) DO UPDATE SET
  name=EXCLUDED.name,
  tier=EXCLUDED.tier,
  description=EXCLUDED.description,
  tagline=EXCLUDED.tagline,
  badge=EXCLUDED.badge,
  cta_label=EXCLUDED.cta_label,
  price_cents=EXCLUDED.price_cents,
  currency=EXCLUDED.currency,
  interval=EXCLUDED.interval,
  trial_days=EXCLUDED.trial_days,
  features=EXCLUDED.features,
  limits=EXCLUDED.limits,
  sort_order=EXCLUDED.sort_order,
  is_active=EXCLUDED.is_active,
  is_public=EXCLUDED.is_public,
  is_custom=EXCLUDED.is_custom,
  highlight=EXCLUDED.highlight,
  monthly_plan_code=EXCLUDED.monthly_plan_code;

-- professional_yearly | year | $182.40
INSERT INTO public.plans (
  code, name, tier, description, tagline, badge, cta_label,
  price_cents, currency, interval, trial_days, features, limits,
  sort_order, is_active, is_public, is_custom, highlight, monthly_plan_code
)
VALUES (
  'professional_yearly',
  'Chuyên nghiệp (hằng năm)',
  'professional',
  'Dành cho doanh nghiệp dịch vụ và đội ngũ bán hàng đang phát triển, cần nhiều hơn một CRM cơ bản. Bổ sung hỗ trợ và tri thức bằng AI, tự động hóa nhiều bước, thử nghiệm chiến dịch, trang tổng quan chuyên sâu và API công khai nhưng vẫn đủ đơn giản để đội ngũ tinh gọn vận hành hằng ngày. Thanh toán hằng năm, tiết kiệm 20% so với trả theo tháng trong 12 tháng.',
  'Vận hành đồng bộ khách hàng, bán hàng, marketing và tự động hóa cho đội ngũ đang phát triển — thanh toán hằng năm và tiết kiệm 20%.',
  'Giá trị tốt nhất',
  'Dùng thử miễn phí',
  18240,
  'USD',
  'year',
  14,
  $features_8$
{
  "ai.reply_assistant": true,
  "ai.knowledge_base": true,
  "automations.enabled": true,
  "marketing.ab_testing": true,
  "marketing.drip_sequences": true,
  "bi.custom_dashboards": true,
  "bi.scheduled_reports": false,
  "api.public_access": true,
  "security.sso": false,
  "security.audit_export": false,
  "inbox": true,
  "broadcasts": true,
  "templates": true,
  "automations": true,
  "chatbot": true,
  "ai": true,
  "crm": true,
  "commerce": true,
  "analytics": true,
  "api": true,
  "white_label": false,
  "sso": false,
  "audit_export": false,
  "sla": false,
  "support": "email",
  "channels": 3
}
$features_8$::jsonb,
  $limits_8$
{
  "seats": 7,
  "organizations": 1,
  "workspaces": 3,
  "contacts": 10000,
  "companies": 2000,
  "deals": 2000,
  "pipelines": 5,
  "campaigns_per_month": 15,
  "broadcasts_per_month": 10000,
  "templates": 50,
  "workflows": 30,
  "ai_requests_per_month": 10000,
  "storage_mb": 5120,
  "api_requests_per_month": 100000,
  "phone_numbers": 3,
  "whatsapp_accounts": 2,
  "custom_fields": 50,
  "reports": 25,
  "exports_per_month": 250,
  "messages_per_month": 10000,
  "agents": 5,
  "storage_gb": 5
}
$limits_8$::jsonb,
  31,
  true,
  true,
  false,
  true,
  'professional'
)
ON CONFLICT (code) DO UPDATE SET
  name=EXCLUDED.name,
  tier=EXCLUDED.tier,
  description=EXCLUDED.description,
  tagline=EXCLUDED.tagline,
  badge=EXCLUDED.badge,
  cta_label=EXCLUDED.cta_label,
  price_cents=EXCLUDED.price_cents,
  currency=EXCLUDED.currency,
  interval=EXCLUDED.interval,
  trial_days=EXCLUDED.trial_days,
  features=EXCLUDED.features,
  limits=EXCLUDED.limits,
  sort_order=EXCLUDED.sort_order,
  is_active=EXCLUDED.is_active,
  is_public=EXCLUDED.is_public,
  is_custom=EXCLUDED.is_custom,
  highlight=EXCLUDED.highlight,
  monthly_plan_code=EXCLUDED.monthly_plan_code;

-- professional_lifetime | lifetime | $599.00
INSERT INTO public.plans (
  code, name, tier, description, tagline, badge, cta_label,
  price_cents, currency, interval, trial_days, features, limits,
  sort_order, is_active, is_public, is_custom, highlight, monthly_plan_code
)
VALUES (
  'professional_lifetime',
  'Chuyên nghiệp trọn đời',
  'professional',
  'Dành cho doanh nghiệp dịch vụ và đội ngũ bán hàng đang phát triển, cần nhiều hơn một CRM cơ bản. Bổ sung hỗ trợ và tri thức bằng AI, tự động hóa nhiều bước, thử nghiệm chiến dịch, trang tổng quan chuyên sâu và API công khai nhưng vẫn đủ đơn giản để đội ngũ tinh gọn vận hành hằng ngày. Đây là giấy phép nền tảng thanh toán một lần cho gói này. Hạn mức sử dụng vẫn theo quy định của gói; chi phí nhắn tin, AI, thoại, đám mây, thanh toán và nhà cung cấp bên thứ ba không được bao gồm trừ khi hợp đồng thương mại nêu rõ.',
  'Thanh toán một lần để sử dụng nền tảng lâu dài với hạn mức gói Chuyên nghiệp.',
  'Ưu đãi riêng',
  'Liên hệ kinh doanh',
  59900,
  'USD',
  'lifetime',
  0,
  $features_9$
{
  "ai.reply_assistant": true,
  "ai.knowledge_base": true,
  "automations.enabled": true,
  "marketing.ab_testing": true,
  "marketing.drip_sequences": true,
  "bi.custom_dashboards": true,
  "bi.scheduled_reports": false,
  "api.public_access": true,
  "security.sso": false,
  "security.audit_export": false,
  "inbox": true,
  "broadcasts": true,
  "templates": true,
  "automations": true,
  "chatbot": true,
  "ai": true,
  "crm": true,
  "commerce": true,
  "analytics": true,
  "api": true,
  "white_label": false,
  "sso": false,
  "audit_export": false,
  "sla": false,
  "support": "email",
  "channels": 3
}
$features_9$::jsonb,
  $limits_9$
{
  "seats": 7,
  "organizations": 1,
  "workspaces": 3,
  "contacts": 10000,
  "companies": 2000,
  "deals": 2000,
  "pipelines": 5,
  "campaigns_per_month": 15,
  "broadcasts_per_month": 10000,
  "templates": 50,
  "workflows": 30,
  "ai_requests_per_month": 10000,
  "storage_mb": 5120,
  "api_requests_per_month": 100000,
  "phone_numbers": 3,
  "whatsapp_accounts": 2,
  "custom_fields": 50,
  "reports": 25,
  "exports_per_month": 250,
  "messages_per_month": 10000,
  "agents": 5,
  "storage_gb": 5
}
$limits_9$::jsonb,
  32,
  true,
  false,
  false,
  false,
  'professional'
)
ON CONFLICT (code) DO UPDATE SET
  name=EXCLUDED.name,
  tier=EXCLUDED.tier,
  description=EXCLUDED.description,
  tagline=EXCLUDED.tagline,
  badge=EXCLUDED.badge,
  cta_label=EXCLUDED.cta_label,
  price_cents=EXCLUDED.price_cents,
  currency=EXCLUDED.currency,
  interval=EXCLUDED.interval,
  trial_days=EXCLUDED.trial_days,
  features=EXCLUDED.features,
  limits=EXCLUDED.limits,
  sort_order=EXCLUDED.sort_order,
  is_active=EXCLUDED.is_active,
  is_public=EXCLUDED.is_public,
  is_custom=EXCLUDED.is_custom,
  highlight=EXCLUDED.highlight,
  monthly_plan_code=EXCLUDED.monthly_plan_code;

-- ═════════════════════════ GROWTH ═════════════════════════

-- growth | month | $39.00
INSERT INTO public.plans (
  code, name, tier, description, tagline, badge, cta_label,
  price_cents, currency, interval, trial_days, features, limits,
  sort_order, is_active, is_public, is_custom, highlight, monthly_plan_code
)
VALUES (
  'growth',
  'Tăng trưởng',
  'growth',
  'Dành cho doanh nghiệp đã vượt qua một quy trình bán hàng đơn lẻ và cần động lực tăng trưởng phối hợp. Quản lý tệp khách hàng lớn hơn, nhiều tự động hóa và chiến dịch hơn, báo cáo theo lịch, nhiều không gian làm việc cùng lưu lượng AI và API cao hơn, trong khi vẫn kết nối marketing, bán hàng và hội thoại khách hàng.',
  'Mở rộng thu hút, nuôi dưỡng và vận hành doanh thu trên nhiều kênh và không gian làm việc.',
  NULL,
  'Dùng thử miễn phí',
  3900,
  'USD',
  'month',
  14,
  $features_10$
{
  "ai.reply_assistant": true,
  "ai.knowledge_base": true,
  "automations.enabled": true,
  "marketing.ab_testing": true,
  "marketing.drip_sequences": true,
  "bi.custom_dashboards": true,
  "bi.scheduled_reports": true,
  "api.public_access": true,
  "security.sso": false,
  "security.audit_export": false,
  "inbox": true,
  "broadcasts": true,
  "templates": true,
  "automations": true,
  "chatbot": true,
  "ai": true,
  "crm": true,
  "commerce": true,
  "analytics": true,
  "api": true,
  "white_label": false,
  "sso": false,
  "audit_export": false,
  "sla": false,
  "support": "priority",
  "channels": 5
}
$features_10$::jsonb,
  $limits_10$
{
  "seats": 15,
  "organizations": 2,
  "workspaces": 5,
  "contacts": 25000,
  "companies": 5000,
  "deals": 5000,
  "pipelines": 10,
  "campaigns_per_month": 40,
  "broadcasts_per_month": 25000,
  "templates": 100,
  "workflows": 75,
  "ai_requests_per_month": 25000,
  "storage_mb": 20480,
  "api_requests_per_month": 300000,
  "phone_numbers": 5,
  "whatsapp_accounts": 3,
  "custom_fields": 150,
  "reports": 50,
  "exports_per_month": 1000,
  "messages_per_month": 25000,
  "agents": 10,
  "storage_gb": 20
}
$limits_10$::jsonb,
  40,
  true,
  true,
  false,
  false,
  NULL
)
ON CONFLICT (code) DO UPDATE SET
  name=EXCLUDED.name,
  tier=EXCLUDED.tier,
  description=EXCLUDED.description,
  tagline=EXCLUDED.tagline,
  badge=EXCLUDED.badge,
  cta_label=EXCLUDED.cta_label,
  price_cents=EXCLUDED.price_cents,
  currency=EXCLUDED.currency,
  interval=EXCLUDED.interval,
  trial_days=EXCLUDED.trial_days,
  features=EXCLUDED.features,
  limits=EXCLUDED.limits,
  sort_order=EXCLUDED.sort_order,
  is_active=EXCLUDED.is_active,
  is_public=EXCLUDED.is_public,
  is_custom=EXCLUDED.is_custom,
  highlight=EXCLUDED.highlight,
  monthly_plan_code=EXCLUDED.monthly_plan_code;

-- growth_yearly | year | $374.40
INSERT INTO public.plans (
  code, name, tier, description, tagline, badge, cta_label,
  price_cents, currency, interval, trial_days, features, limits,
  sort_order, is_active, is_public, is_custom, highlight, monthly_plan_code
)
VALUES (
  'growth_yearly',
  'Tăng trưởng (hằng năm)',
  'growth',
  'Dành cho doanh nghiệp đã vượt qua một quy trình bán hàng đơn lẻ và cần động lực tăng trưởng phối hợp. Quản lý tệp khách hàng lớn hơn, nhiều tự động hóa và chiến dịch hơn, báo cáo theo lịch, nhiều không gian làm việc cùng lưu lượng AI và API cao hơn, trong khi vẫn kết nối marketing, bán hàng và hội thoại khách hàng. Thanh toán hằng năm, tiết kiệm 20% so với trả theo tháng trong 12 tháng.',
  'Mở rộng thu hút, nuôi dưỡng và vận hành doanh thu trên nhiều kênh và không gian làm việc — thanh toán hằng năm và tiết kiệm 20%.',
  NULL,
  'Dùng thử miễn phí',
  37440,
  'USD',
  'year',
  14,
  $features_11$
{
  "ai.reply_assistant": true,
  "ai.knowledge_base": true,
  "automations.enabled": true,
  "marketing.ab_testing": true,
  "marketing.drip_sequences": true,
  "bi.custom_dashboards": true,
  "bi.scheduled_reports": true,
  "api.public_access": true,
  "security.sso": false,
  "security.audit_export": false,
  "inbox": true,
  "broadcasts": true,
  "templates": true,
  "automations": true,
  "chatbot": true,
  "ai": true,
  "crm": true,
  "commerce": true,
  "analytics": true,
  "api": true,
  "white_label": false,
  "sso": false,
  "audit_export": false,
  "sla": false,
  "support": "priority",
  "channels": 5
}
$features_11$::jsonb,
  $limits_11$
{
  "seats": 15,
  "organizations": 2,
  "workspaces": 5,
  "contacts": 25000,
  "companies": 5000,
  "deals": 5000,
  "pipelines": 10,
  "campaigns_per_month": 40,
  "broadcasts_per_month": 25000,
  "templates": 100,
  "workflows": 75,
  "ai_requests_per_month": 25000,
  "storage_mb": 20480,
  "api_requests_per_month": 300000,
  "phone_numbers": 5,
  "whatsapp_accounts": 3,
  "custom_fields": 150,
  "reports": 50,
  "exports_per_month": 1000,
  "messages_per_month": 25000,
  "agents": 10,
  "storage_gb": 20
}
$limits_11$::jsonb,
  41,
  true,
  true,
  false,
  false,
  'growth'
)
ON CONFLICT (code) DO UPDATE SET
  name=EXCLUDED.name,
  tier=EXCLUDED.tier,
  description=EXCLUDED.description,
  tagline=EXCLUDED.tagline,
  badge=EXCLUDED.badge,
  cta_label=EXCLUDED.cta_label,
  price_cents=EXCLUDED.price_cents,
  currency=EXCLUDED.currency,
  interval=EXCLUDED.interval,
  trial_days=EXCLUDED.trial_days,
  features=EXCLUDED.features,
  limits=EXCLUDED.limits,
  sort_order=EXCLUDED.sort_order,
  is_active=EXCLUDED.is_active,
  is_public=EXCLUDED.is_public,
  is_custom=EXCLUDED.is_custom,
  highlight=EXCLUDED.highlight,
  monthly_plan_code=EXCLUDED.monthly_plan_code;

-- growth_lifetime | lifetime | $1,199.00
INSERT INTO public.plans (
  code, name, tier, description, tagline, badge, cta_label,
  price_cents, currency, interval, trial_days, features, limits,
  sort_order, is_active, is_public, is_custom, highlight, monthly_plan_code
)
VALUES (
  'growth_lifetime',
  'Tăng trưởng trọn đời',
  'growth',
  'Dành cho doanh nghiệp đã vượt qua một quy trình bán hàng đơn lẻ và cần động lực tăng trưởng phối hợp. Quản lý tệp khách hàng lớn hơn, nhiều tự động hóa và chiến dịch hơn, báo cáo theo lịch, nhiều không gian làm việc cùng lưu lượng AI và API cao hơn, trong khi vẫn kết nối marketing, bán hàng và hội thoại khách hàng. Đây là giấy phép nền tảng thanh toán một lần cho gói này. Hạn mức sử dụng vẫn theo quy định của gói; chi phí nhắn tin, AI, thoại, đám mây, thanh toán và nhà cung cấp bên thứ ba không được bao gồm trừ khi hợp đồng thương mại nêu rõ.',
  'Thanh toán một lần để sử dụng nền tảng lâu dài với hạn mức gói Tăng trưởng.',
  'Ưu đãi riêng',
  'Liên hệ kinh doanh',
  119900,
  'USD',
  'lifetime',
  0,
  $features_12$
{
  "ai.reply_assistant": true,
  "ai.knowledge_base": true,
  "automations.enabled": true,
  "marketing.ab_testing": true,
  "marketing.drip_sequences": true,
  "bi.custom_dashboards": true,
  "bi.scheduled_reports": true,
  "api.public_access": true,
  "security.sso": false,
  "security.audit_export": false,
  "inbox": true,
  "broadcasts": true,
  "templates": true,
  "automations": true,
  "chatbot": true,
  "ai": true,
  "crm": true,
  "commerce": true,
  "analytics": true,
  "api": true,
  "white_label": false,
  "sso": false,
  "audit_export": false,
  "sla": false,
  "support": "priority",
  "channels": 5
}
$features_12$::jsonb,
  $limits_12$
{
  "seats": 15,
  "organizations": 2,
  "workspaces": 5,
  "contacts": 25000,
  "companies": 5000,
  "deals": 5000,
  "pipelines": 10,
  "campaigns_per_month": 40,
  "broadcasts_per_month": 25000,
  "templates": 100,
  "workflows": 75,
  "ai_requests_per_month": 25000,
  "storage_mb": 20480,
  "api_requests_per_month": 300000,
  "phone_numbers": 5,
  "whatsapp_accounts": 3,
  "custom_fields": 150,
  "reports": 50,
  "exports_per_month": 1000,
  "messages_per_month": 25000,
  "agents": 10,
  "storage_gb": 20
}
$limits_12$::jsonb,
  42,
  true,
  false,
  false,
  false,
  'growth'
)
ON CONFLICT (code) DO UPDATE SET
  name=EXCLUDED.name,
  tier=EXCLUDED.tier,
  description=EXCLUDED.description,
  tagline=EXCLUDED.tagline,
  badge=EXCLUDED.badge,
  cta_label=EXCLUDED.cta_label,
  price_cents=EXCLUDED.price_cents,
  currency=EXCLUDED.currency,
  interval=EXCLUDED.interval,
  trial_days=EXCLUDED.trial_days,
  features=EXCLUDED.features,
  limits=EXCLUDED.limits,
  sort_order=EXCLUDED.sort_order,
  is_active=EXCLUDED.is_active,
  is_public=EXCLUDED.is_public,
  is_custom=EXCLUDED.is_custom,
  highlight=EXCLUDED.highlight,
  monthly_plan_code=EXCLUDED.monthly_plan_code;

-- ═════════════════════════ BUSINESS ═════════════════════════

-- business | month | $79.00
INSERT INTO public.plans (
  code, name, tier, description, tagline, badge, cta_label,
  price_cents, currency, interval, trial_days, features, limits,
  sort_order, is_active, is_public, is_custom, highlight, monthly_plan_code
)
VALUES (
  'business',
  'Doanh nghiệp',
  'business',
  'Dành cho doanh nghiệp ổn định đang vận hành nhiều đội nhóm, không gian làm việc, thương hiệu hoặc chương trình khách hàng. Bổ sung hạn mức vận hành cao hơn đáng kể, SSO, xuất nhật ký kiểm tra, báo cáo nâng cao, dung lượng API và kiểm soát quản trị để mở rộng thu hút khách hàng, bán hàng, dịch vụ và tự động hóa mà vẫn giữ được khả năng giám sát.',
  'Chuẩn hóa vận hành doanh thu đa đội nhóm với quản trị, bảo mật và dung lượng cao hơn.',
  NULL,
  'Dùng thử miễn phí',
  7900,
  'USD',
  'month',
  14,
  $features_13$
{
  "ai.reply_assistant": true,
  "ai.knowledge_base": true,
  "automations.enabled": true,
  "marketing.ab_testing": true,
  "marketing.drip_sequences": true,
  "bi.custom_dashboards": true,
  "bi.scheduled_reports": true,
  "api.public_access": true,
  "security.sso": true,
  "security.audit_export": true,
  "inbox": true,
  "broadcasts": true,
  "templates": true,
  "automations": true,
  "chatbot": true,
  "ai": true,
  "crm": true,
  "commerce": true,
  "analytics": true,
  "api": true,
  "white_label": false,
  "sso": true,
  "audit_export": true,
  "sla": false,
  "support": "priority",
  "channels": 10
}
$features_13$::jsonb,
  $limits_13$
{
  "seats": 30,
  "organizations": 5,
  "workspaces": 15,
  "contacts": 100000,
  "companies": 25000,
  "deals": 25000,
  "pipelines": 25,
  "campaigns_per_month": 100,
  "broadcasts_per_month": 100000,
  "templates": 300,
  "workflows": 250,
  "ai_requests_per_month": 100000,
  "storage_mb": 102400,
  "api_requests_per_month": 1000000,
  "phone_numbers": 15,
  "whatsapp_accounts": 10,
  "custom_fields": 500,
  "reports": 200,
  "exports_per_month": 5000,
  "messages_per_month": 100000,
  "agents": 25,
  "storage_gb": 100
}
$limits_13$::jsonb,
  50,
  true,
  true,
  false,
  false,
  NULL
)
ON CONFLICT (code) DO UPDATE SET
  name=EXCLUDED.name,
  tier=EXCLUDED.tier,
  description=EXCLUDED.description,
  tagline=EXCLUDED.tagline,
  badge=EXCLUDED.badge,
  cta_label=EXCLUDED.cta_label,
  price_cents=EXCLUDED.price_cents,
  currency=EXCLUDED.currency,
  interval=EXCLUDED.interval,
  trial_days=EXCLUDED.trial_days,
  features=EXCLUDED.features,
  limits=EXCLUDED.limits,
  sort_order=EXCLUDED.sort_order,
  is_active=EXCLUDED.is_active,
  is_public=EXCLUDED.is_public,
  is_custom=EXCLUDED.is_custom,
  highlight=EXCLUDED.highlight,
  monthly_plan_code=EXCLUDED.monthly_plan_code;

-- business_yearly | year | $758.40
INSERT INTO public.plans (
  code, name, tier, description, tagline, badge, cta_label,
  price_cents, currency, interval, trial_days, features, limits,
  sort_order, is_active, is_public, is_custom, highlight, monthly_plan_code
)
VALUES (
  'business_yearly',
  'Doanh nghiệp (hằng năm)',
  'business',
  'Dành cho doanh nghiệp ổn định đang vận hành nhiều đội nhóm, không gian làm việc, thương hiệu hoặc chương trình khách hàng. Bổ sung hạn mức vận hành cao hơn đáng kể, SSO, xuất nhật ký kiểm tra, báo cáo nâng cao, dung lượng API và kiểm soát quản trị để mở rộng thu hút khách hàng, bán hàng, dịch vụ và tự động hóa mà vẫn giữ được khả năng giám sát. Thanh toán hằng năm, tiết kiệm 20% so với trả theo tháng trong 12 tháng.',
  'Chuẩn hóa vận hành doanh thu đa đội nhóm với quản trị, bảo mật và dung lượng cao hơn — thanh toán hằng năm và tiết kiệm 20%.',
  NULL,
  'Dùng thử miễn phí',
  75840,
  'USD',
  'year',
  14,
  $features_14$
{
  "ai.reply_assistant": true,
  "ai.knowledge_base": true,
  "automations.enabled": true,
  "marketing.ab_testing": true,
  "marketing.drip_sequences": true,
  "bi.custom_dashboards": true,
  "bi.scheduled_reports": true,
  "api.public_access": true,
  "security.sso": true,
  "security.audit_export": true,
  "inbox": true,
  "broadcasts": true,
  "templates": true,
  "automations": true,
  "chatbot": true,
  "ai": true,
  "crm": true,
  "commerce": true,
  "analytics": true,
  "api": true,
  "white_label": false,
  "sso": true,
  "audit_export": true,
  "sla": false,
  "support": "priority",
  "channels": 10
}
$features_14$::jsonb,
  $limits_14$
{
  "seats": 30,
  "organizations": 5,
  "workspaces": 15,
  "contacts": 100000,
  "companies": 25000,
  "deals": 25000,
  "pipelines": 25,
  "campaigns_per_month": 100,
  "broadcasts_per_month": 100000,
  "templates": 300,
  "workflows": 250,
  "ai_requests_per_month": 100000,
  "storage_mb": 102400,
  "api_requests_per_month": 1000000,
  "phone_numbers": 15,
  "whatsapp_accounts": 10,
  "custom_fields": 500,
  "reports": 200,
  "exports_per_month": 5000,
  "messages_per_month": 100000,
  "agents": 25,
  "storage_gb": 100
}
$limits_14$::jsonb,
  51,
  true,
  true,
  false,
  false,
  'business'
)
ON CONFLICT (code) DO UPDATE SET
  name=EXCLUDED.name,
  tier=EXCLUDED.tier,
  description=EXCLUDED.description,
  tagline=EXCLUDED.tagline,
  badge=EXCLUDED.badge,
  cta_label=EXCLUDED.cta_label,
  price_cents=EXCLUDED.price_cents,
  currency=EXCLUDED.currency,
  interval=EXCLUDED.interval,
  trial_days=EXCLUDED.trial_days,
  features=EXCLUDED.features,
  limits=EXCLUDED.limits,
  sort_order=EXCLUDED.sort_order,
  is_active=EXCLUDED.is_active,
  is_public=EXCLUDED.is_public,
  is_custom=EXCLUDED.is_custom,
  highlight=EXCLUDED.highlight,
  monthly_plan_code=EXCLUDED.monthly_plan_code;

-- business_lifetime | lifetime | $2,399.00
INSERT INTO public.plans (
  code, name, tier, description, tagline, badge, cta_label,
  price_cents, currency, interval, trial_days, features, limits,
  sort_order, is_active, is_public, is_custom, highlight, monthly_plan_code
)
VALUES (
  'business_lifetime',
  'Doanh nghiệp trọn đời',
  'business',
  'Dành cho doanh nghiệp ổn định đang vận hành nhiều đội nhóm, không gian làm việc, thương hiệu hoặc chương trình khách hàng. Bổ sung hạn mức vận hành cao hơn đáng kể, SSO, xuất nhật ký kiểm tra, báo cáo nâng cao, dung lượng API và kiểm soát quản trị để mở rộng thu hút khách hàng, bán hàng, dịch vụ và tự động hóa mà vẫn giữ được khả năng giám sát. Đây là giấy phép nền tảng thanh toán một lần cho gói này. Hạn mức sử dụng vẫn theo quy định của gói; chi phí nhắn tin, AI, thoại, đám mây, thanh toán và nhà cung cấp bên thứ ba không được bao gồm trừ khi hợp đồng thương mại nêu rõ.',
  'Thanh toán một lần để sử dụng nền tảng lâu dài với hạn mức gói Doanh nghiệp.',
  'Ưu đãi riêng',
  'Liên hệ kinh doanh',
  239900,
  'USD',
  'lifetime',
  0,
  $features_15$
{
  "ai.reply_assistant": true,
  "ai.knowledge_base": true,
  "automations.enabled": true,
  "marketing.ab_testing": true,
  "marketing.drip_sequences": true,
  "bi.custom_dashboards": true,
  "bi.scheduled_reports": true,
  "api.public_access": true,
  "security.sso": true,
  "security.audit_export": true,
  "inbox": true,
  "broadcasts": true,
  "templates": true,
  "automations": true,
  "chatbot": true,
  "ai": true,
  "crm": true,
  "commerce": true,
  "analytics": true,
  "api": true,
  "white_label": false,
  "sso": true,
  "audit_export": true,
  "sla": false,
  "support": "priority",
  "channels": 10
}
$features_15$::jsonb,
  $limits_15$
{
  "seats": 30,
  "organizations": 5,
  "workspaces": 15,
  "contacts": 100000,
  "companies": 25000,
  "deals": 25000,
  "pipelines": 25,
  "campaigns_per_month": 100,
  "broadcasts_per_month": 100000,
  "templates": 300,
  "workflows": 250,
  "ai_requests_per_month": 100000,
  "storage_mb": 102400,
  "api_requests_per_month": 1000000,
  "phone_numbers": 15,
  "whatsapp_accounts": 10,
  "custom_fields": 500,
  "reports": 200,
  "exports_per_month": 5000,
  "messages_per_month": 100000,
  "agents": 25,
  "storage_gb": 100
}
$limits_15$::jsonb,
  52,
  true,
  false,
  false,
  false,
  'business'
)
ON CONFLICT (code) DO UPDATE SET
  name=EXCLUDED.name,
  tier=EXCLUDED.tier,
  description=EXCLUDED.description,
  tagline=EXCLUDED.tagline,
  badge=EXCLUDED.badge,
  cta_label=EXCLUDED.cta_label,
  price_cents=EXCLUDED.price_cents,
  currency=EXCLUDED.currency,
  interval=EXCLUDED.interval,
  trial_days=EXCLUDED.trial_days,
  features=EXCLUDED.features,
  limits=EXCLUDED.limits,
  sort_order=EXCLUDED.sort_order,
  is_active=EXCLUDED.is_active,
  is_public=EXCLUDED.is_public,
  is_custom=EXCLUDED.is_custom,
  highlight=EXCLUDED.highlight,
  monthly_plan_code=EXCLUDED.monthly_plan_code;

-- ═════════════════════════ ENTERPRISE ═════════════════════════

-- enterprise | month | $199.00
INSERT INTO public.plans (
  code, name, tier, description, tagline, badge, cta_label,
  price_cents, currency, interval, trial_days, features, limits,
  sort_order, is_active, is_public, is_custom, highlight, monthly_plan_code
)
VALUES (
  'enterprise',
  'Doanh nghiệp lớn',
  'enterprise',
  'Gói có tư vấn bán hàng dành cho tổ chức lớn cần dung lượng vận hành cao, quản trị chặt chẽ hơn, tùy chọn nhãn riêng, SSO, khả năng kiểm tra, hỗ trợ theo SLA và hướng dẫn triển khai. Hạn mức mặc định tạo nền tảng an toàn cho doanh nghiệp lớn và có thể điều chỉnh theo thỏa thuận thương mại khi cần thêm dung lượng.',
  'Vận hành quy trình khách hàng và doanh thu quy mô lớn với kiểm soát cấp doanh nghiệp và hỗ trợ riêng.',
  'Liên hệ kinh doanh',
  'Liên hệ kinh doanh',
  19900,
  'USD',
  'month',
  0,
  $features_16$
{
  "ai.reply_assistant": true,
  "ai.knowledge_base": true,
  "automations.enabled": true,
  "marketing.ab_testing": true,
  "marketing.drip_sequences": true,
  "bi.custom_dashboards": true,
  "bi.scheduled_reports": true,
  "api.public_access": true,
  "security.sso": true,
  "security.audit_export": true,
  "inbox": true,
  "broadcasts": true,
  "templates": true,
  "automations": true,
  "chatbot": true,
  "ai": true,
  "crm": true,
  "commerce": true,
  "analytics": true,
  "api": true,
  "white_label": true,
  "sso": true,
  "audit_export": true,
  "sla": true,
  "support": "dedicated",
  "channels": 25
}
$features_16$::jsonb,
  $limits_16$
{
  "seats": 100,
  "organizations": 10,
  "workspaces": 50,
  "contacts": 500000,
  "companies": 100000,
  "deals": 100000,
  "pipelines": 100,
  "campaigns_per_month": 500,
  "broadcasts_per_month": 500000,
  "templates": 1000,
  "workflows": 1000,
  "ai_requests_per_month": 500000,
  "storage_mb": 524288,
  "api_requests_per_month": 5000000,
  "phone_numbers": 50,
  "whatsapp_accounts": 25,
  "custom_fields": 2000,
  "reports": 1000,
  "exports_per_month": 20000,
  "messages_per_month": 500000,
  "agents": 100,
  "storage_gb": 512
}
$limits_16$::jsonb,
  60,
  true,
  true,
  false,
  false,
  NULL
)
ON CONFLICT (code) DO UPDATE SET
  name=EXCLUDED.name,
  tier=EXCLUDED.tier,
  description=EXCLUDED.description,
  tagline=EXCLUDED.tagline,
  badge=EXCLUDED.badge,
  cta_label=EXCLUDED.cta_label,
  price_cents=EXCLUDED.price_cents,
  currency=EXCLUDED.currency,
  interval=EXCLUDED.interval,
  trial_days=EXCLUDED.trial_days,
  features=EXCLUDED.features,
  limits=EXCLUDED.limits,
  sort_order=EXCLUDED.sort_order,
  is_active=EXCLUDED.is_active,
  is_public=EXCLUDED.is_public,
  is_custom=EXCLUDED.is_custom,
  highlight=EXCLUDED.highlight,
  monthly_plan_code=EXCLUDED.monthly_plan_code;

-- enterprise_yearly | year | $1,910.40
INSERT INTO public.plans (
  code, name, tier, description, tagline, badge, cta_label,
  price_cents, currency, interval, trial_days, features, limits,
  sort_order, is_active, is_public, is_custom, highlight, monthly_plan_code
)
VALUES (
  'enterprise_yearly',
  'Doanh nghiệp lớn (hằng năm)',
  'enterprise',
  'Gói có tư vấn bán hàng dành cho tổ chức lớn cần dung lượng vận hành cao, quản trị chặt chẽ hơn, tùy chọn nhãn riêng, SSO, khả năng kiểm tra, hỗ trợ theo SLA và hướng dẫn triển khai. Hạn mức mặc định tạo nền tảng an toàn cho doanh nghiệp lớn và có thể điều chỉnh theo thỏa thuận thương mại khi cần thêm dung lượng. Thanh toán hằng năm, tiết kiệm 20% so với trả theo tháng trong 12 tháng.',
  'Vận hành quy trình khách hàng và doanh thu quy mô lớn với kiểm soát cấp doanh nghiệp và hỗ trợ riêng — thanh toán hằng năm và tiết kiệm 20%.',
  'Liên hệ kinh doanh',
  'Liên hệ kinh doanh',
  191040,
  'USD',
  'year',
  0,
  $features_17$
{
  "ai.reply_assistant": true,
  "ai.knowledge_base": true,
  "automations.enabled": true,
  "marketing.ab_testing": true,
  "marketing.drip_sequences": true,
  "bi.custom_dashboards": true,
  "bi.scheduled_reports": true,
  "api.public_access": true,
  "security.sso": true,
  "security.audit_export": true,
  "inbox": true,
  "broadcasts": true,
  "templates": true,
  "automations": true,
  "chatbot": true,
  "ai": true,
  "crm": true,
  "commerce": true,
  "analytics": true,
  "api": true,
  "white_label": true,
  "sso": true,
  "audit_export": true,
  "sla": true,
  "support": "dedicated",
  "channels": 25
}
$features_17$::jsonb,
  $limits_17$
{
  "seats": 100,
  "organizations": 10,
  "workspaces": 50,
  "contacts": 500000,
  "companies": 100000,
  "deals": 100000,
  "pipelines": 100,
  "campaigns_per_month": 500,
  "broadcasts_per_month": 500000,
  "templates": 1000,
  "workflows": 1000,
  "ai_requests_per_month": 500000,
  "storage_mb": 524288,
  "api_requests_per_month": 5000000,
  "phone_numbers": 50,
  "whatsapp_accounts": 25,
  "custom_fields": 2000,
  "reports": 1000,
  "exports_per_month": 20000,
  "messages_per_month": 500000,
  "agents": 100,
  "storage_gb": 512
}
$limits_17$::jsonb,
  61,
  true,
  false,
  false,
  false,
  'enterprise'
)
ON CONFLICT (code) DO UPDATE SET
  name=EXCLUDED.name,
  tier=EXCLUDED.tier,
  description=EXCLUDED.description,
  tagline=EXCLUDED.tagline,
  badge=EXCLUDED.badge,
  cta_label=EXCLUDED.cta_label,
  price_cents=EXCLUDED.price_cents,
  currency=EXCLUDED.currency,
  interval=EXCLUDED.interval,
  trial_days=EXCLUDED.trial_days,
  features=EXCLUDED.features,
  limits=EXCLUDED.limits,
  sort_order=EXCLUDED.sort_order,
  is_active=EXCLUDED.is_active,
  is_public=EXCLUDED.is_public,
  is_custom=EXCLUDED.is_custom,
  highlight=EXCLUDED.highlight,
  monthly_plan_code=EXCLUDED.monthly_plan_code;

-- enterprise_lifetime | lifetime | $5,999.00
INSERT INTO public.plans (
  code, name, tier, description, tagline, badge, cta_label,
  price_cents, currency, interval, trial_days, features, limits,
  sort_order, is_active, is_public, is_custom, highlight, monthly_plan_code
)
VALUES (
  'enterprise_lifetime',
  'Doanh nghiệp lớn trọn đời',
  'enterprise',
  'Gói có tư vấn bán hàng dành cho tổ chức lớn cần dung lượng vận hành cao, quản trị chặt chẽ hơn, tùy chọn nhãn riêng, SSO, khả năng kiểm tra, hỗ trợ theo SLA và hướng dẫn triển khai. Hạn mức mặc định tạo nền tảng an toàn cho doanh nghiệp lớn và có thể điều chỉnh theo thỏa thuận thương mại khi cần thêm dung lượng. Đây là giấy phép nền tảng thanh toán một lần cho gói này. Hạn mức sử dụng vẫn theo quy định của gói; chi phí nhắn tin, AI, thoại, đám mây, thanh toán và nhà cung cấp bên thứ ba không được bao gồm trừ khi hợp đồng thương mại nêu rõ.',
  'Thanh toán một lần để sử dụng nền tảng lâu dài với hạn mức gói Doanh nghiệp lớn.',
  'Ưu đãi riêng',
  'Liên hệ kinh doanh',
  599900,
  'USD',
  'lifetime',
  0,
  $features_18$
{
  "ai.reply_assistant": true,
  "ai.knowledge_base": true,
  "automations.enabled": true,
  "marketing.ab_testing": true,
  "marketing.drip_sequences": true,
  "bi.custom_dashboards": true,
  "bi.scheduled_reports": true,
  "api.public_access": true,
  "security.sso": true,
  "security.audit_export": true,
  "inbox": true,
  "broadcasts": true,
  "templates": true,
  "automations": true,
  "chatbot": true,
  "ai": true,
  "crm": true,
  "commerce": true,
  "analytics": true,
  "api": true,
  "white_label": true,
  "sso": true,
  "audit_export": true,
  "sla": true,
  "support": "dedicated",
  "channels": 25
}
$features_18$::jsonb,
  $limits_18$
{
  "seats": 100,
  "organizations": 10,
  "workspaces": 50,
  "contacts": 500000,
  "companies": 100000,
  "deals": 100000,
  "pipelines": 100,
  "campaigns_per_month": 500,
  "broadcasts_per_month": 500000,
  "templates": 1000,
  "workflows": 1000,
  "ai_requests_per_month": 500000,
  "storage_mb": 524288,
  "api_requests_per_month": 5000000,
  "phone_numbers": 50,
  "whatsapp_accounts": 25,
  "custom_fields": 2000,
  "reports": 1000,
  "exports_per_month": 20000,
  "messages_per_month": 500000,
  "agents": 100,
  "storage_gb": 512
}
$limits_18$::jsonb,
  62,
  true,
  false,
  false,
  false,
  'enterprise'
)
ON CONFLICT (code) DO UPDATE SET
  name=EXCLUDED.name,
  tier=EXCLUDED.tier,
  description=EXCLUDED.description,
  tagline=EXCLUDED.tagline,
  badge=EXCLUDED.badge,
  cta_label=EXCLUDED.cta_label,
  price_cents=EXCLUDED.price_cents,
  currency=EXCLUDED.currency,
  interval=EXCLUDED.interval,
  trial_days=EXCLUDED.trial_days,
  features=EXCLUDED.features,
  limits=EXCLUDED.limits,
  sort_order=EXCLUDED.sort_order,
  is_active=EXCLUDED.is_active,
  is_public=EXCLUDED.is_public,
  is_custom=EXCLUDED.is_custom,
  highlight=EXCLUDED.highlight,
  monthly_plan_code=EXCLUDED.monthly_plan_code;

-- ═════════════════════════ CUSTOM ═════════════════════════

-- custom | month | $0.00
INSERT INTO public.plans (
  code, name, tier, description, tagline, badge, cta_label,
  price_cents, currency, interval, trial_days, features, limits,
  sort_order, is_active, is_public, is_custom, highlight, monthly_plan_code
)
VALUES (
  'custom',
  'Tùy chỉnh',
  'custom',
  'Mẫu gói riêng cho các triển khai không phù hợp với hệ gói tiêu chuẩn. Dùng cho dung lượng thương lượng, tích hợp tùy chỉnh, yêu cầu lưu trữ hoặc dữ liệu đặc biệt, dịch vụ triển khai, thỏa thuận đại lý hoặc điều khoản thương mại khác. Hạn mức khởi tạo chỉ là giá trị thận trọng và cần được xem xét trước khi gán gói cho khách hàng.',
  'Gói triển khai theo thỏa thuận dành cho tổ chức có yêu cầu riêng về hạn mức, tích hợp, lưu trữ hoặc điều khoản thương mại.',
  'Theo nhu cầu',
  'Liên hệ kinh doanh',
  0,
  'USD',
  'month',
  0,
  $features_19$
{
  "ai.reply_assistant": true,
  "ai.knowledge_base": true,
  "automations.enabled": true,
  "marketing.ab_testing": true,
  "marketing.drip_sequences": true,
  "bi.custom_dashboards": true,
  "bi.scheduled_reports": true,
  "api.public_access": true,
  "security.sso": true,
  "security.audit_export": true,
  "inbox": true,
  "broadcasts": true,
  "templates": true,
  "automations": true,
  "chatbot": true,
  "ai": true,
  "crm": true,
  "commerce": true,
  "analytics": true,
  "api": true,
  "white_label": true,
  "sso": true,
  "audit_export": true,
  "sla": true,
  "support": "dedicated",
  "channels": 25
}
$features_19$::jsonb,
  $limits_19$
{
  "seats": 100,
  "organizations": 10,
  "workspaces": 50,
  "contacts": 500000,
  "companies": 100000,
  "deals": 100000,
  "pipelines": 100,
  "campaigns_per_month": 500,
  "broadcasts_per_month": 500000,
  "templates": 1000,
  "workflows": 1000,
  "ai_requests_per_month": 500000,
  "storage_mb": 524288,
  "api_requests_per_month": 5000000,
  "phone_numbers": 50,
  "whatsapp_accounts": 25,
  "custom_fields": 2000,
  "reports": 1000,
  "exports_per_month": 20000,
  "messages_per_month": 500000,
  "agents": 100,
  "storage_gb": 512
}
$limits_19$::jsonb,
  70,
  false,
  false,
  true,
  false,
  NULL
)
ON CONFLICT (code) DO UPDATE SET
  name=EXCLUDED.name,
  tier=EXCLUDED.tier,
  description=EXCLUDED.description,
  tagline=EXCLUDED.tagline,
  badge=EXCLUDED.badge,
  cta_label=EXCLUDED.cta_label,
  price_cents=EXCLUDED.price_cents,
  currency=EXCLUDED.currency,
  interval=EXCLUDED.interval,
  trial_days=EXCLUDED.trial_days,
  features=EXCLUDED.features,
  limits=EXCLUDED.limits,
  sort_order=EXCLUDED.sort_order,
  is_active=EXCLUDED.is_active,
  is_public=EXCLUDED.is_public,
  is_custom=EXCLUDED.is_custom,
  highlight=EXCLUDED.highlight,
  monthly_plan_code=EXCLUDED.monthly_plan_code;

-- custom_yearly | year | $0.00
INSERT INTO public.plans (
  code, name, tier, description, tagline, badge, cta_label,
  price_cents, currency, interval, trial_days, features, limits,
  sort_order, is_active, is_public, is_custom, highlight, monthly_plan_code
)
VALUES (
  'custom_yearly',
  'Tùy chỉnh (hằng năm)',
  'custom',
  'Mẫu gói riêng cho các triển khai không phù hợp với hệ gói tiêu chuẩn. Dùng cho dung lượng thương lượng, tích hợp tùy chỉnh, yêu cầu lưu trữ hoặc dữ liệu đặc biệt, dịch vụ triển khai, thỏa thuận đại lý hoặc điều khoản thương mại khác. Hạn mức khởi tạo chỉ là giá trị thận trọng và cần được xem xét trước khi gán gói cho khách hàng. Giá và quyền lợi được xác lập trong thỏa thuận thương mại riêng.',
  'Hợp đồng hằng năm riêng được cấu hình theo các yêu cầu đã thương lượng.',
  'Theo nhu cầu',
  'Liên hệ kinh doanh',
  0,
  'USD',
  'year',
  0,
  $features_20$
{
  "ai.reply_assistant": true,
  "ai.knowledge_base": true,
  "automations.enabled": true,
  "marketing.ab_testing": true,
  "marketing.drip_sequences": true,
  "bi.custom_dashboards": true,
  "bi.scheduled_reports": true,
  "api.public_access": true,
  "security.sso": true,
  "security.audit_export": true,
  "inbox": true,
  "broadcasts": true,
  "templates": true,
  "automations": true,
  "chatbot": true,
  "ai": true,
  "crm": true,
  "commerce": true,
  "analytics": true,
  "api": true,
  "white_label": true,
  "sso": true,
  "audit_export": true,
  "sla": true,
  "support": "dedicated",
  "channels": 25
}
$features_20$::jsonb,
  $limits_20$
{
  "seats": 100,
  "organizations": 10,
  "workspaces": 50,
  "contacts": 500000,
  "companies": 100000,
  "deals": 100000,
  "pipelines": 100,
  "campaigns_per_month": 500,
  "broadcasts_per_month": 500000,
  "templates": 1000,
  "workflows": 1000,
  "ai_requests_per_month": 500000,
  "storage_mb": 524288,
  "api_requests_per_month": 5000000,
  "phone_numbers": 50,
  "whatsapp_accounts": 25,
  "custom_fields": 2000,
  "reports": 1000,
  "exports_per_month": 20000,
  "messages_per_month": 500000,
  "agents": 100,
  "storage_gb": 512
}
$limits_20$::jsonb,
  71,
  false,
  false,
  true,
  false,
  'custom'
)
ON CONFLICT (code) DO UPDATE SET
  name=EXCLUDED.name,
  tier=EXCLUDED.tier,
  description=EXCLUDED.description,
  tagline=EXCLUDED.tagline,
  badge=EXCLUDED.badge,
  cta_label=EXCLUDED.cta_label,
  price_cents=EXCLUDED.price_cents,
  currency=EXCLUDED.currency,
  interval=EXCLUDED.interval,
  trial_days=EXCLUDED.trial_days,
  features=EXCLUDED.features,
  limits=EXCLUDED.limits,
  sort_order=EXCLUDED.sort_order,
  is_active=EXCLUDED.is_active,
  is_public=EXCLUDED.is_public,
  is_custom=EXCLUDED.is_custom,
  highlight=EXCLUDED.highlight,
  monthly_plan_code=EXCLUDED.monthly_plan_code;

-- custom_lifetime | lifetime | $0.00
INSERT INTO public.plans (
  code, name, tier, description, tagline, badge, cta_label,
  price_cents, currency, interval, trial_days, features, limits,
  sort_order, is_active, is_public, is_custom, highlight, monthly_plan_code
)
VALUES (
  'custom_lifetime',
  'Tùy chỉnh trọn đời',
  'custom',
  'Mẫu gói riêng cho các triển khai không phù hợp với hệ gói tiêu chuẩn. Dùng cho dung lượng thương lượng, tích hợp tùy chỉnh, yêu cầu lưu trữ hoặc dữ liệu đặc biệt, dịch vụ triển khai, thỏa thuận đại lý hoặc điều khoản thương mại khác. Hạn mức khởi tạo chỉ là giá trị thận trọng và cần được xem xét trước khi gán gói cho khách hàng. Phạm vi thương mại, triển khai, lưu trữ và chi phí nhà cung cấp phải được xác định trong hợp đồng đã ký.',
  'Thỏa thuận tùy chỉnh thanh toán một lần cho một triển khai được thương lượng riêng.',
  'Theo nhu cầu',
  'Liên hệ kinh doanh',
  0,
  'USD',
  'lifetime',
  0,
  $features_21$
{
  "ai.reply_assistant": true,
  "ai.knowledge_base": true,
  "automations.enabled": true,
  "marketing.ab_testing": true,
  "marketing.drip_sequences": true,
  "bi.custom_dashboards": true,
  "bi.scheduled_reports": true,
  "api.public_access": true,
  "security.sso": true,
  "security.audit_export": true,
  "inbox": true,
  "broadcasts": true,
  "templates": true,
  "automations": true,
  "chatbot": true,
  "ai": true,
  "crm": true,
  "commerce": true,
  "analytics": true,
  "api": true,
  "white_label": true,
  "sso": true,
  "audit_export": true,
  "sla": true,
  "support": "dedicated",
  "channels": 25
}
$features_21$::jsonb,
  $limits_21$
{
  "seats": 100,
  "organizations": 10,
  "workspaces": 50,
  "contacts": 500000,
  "companies": 100000,
  "deals": 100000,
  "pipelines": 100,
  "campaigns_per_month": 500,
  "broadcasts_per_month": 500000,
  "templates": 1000,
  "workflows": 1000,
  "ai_requests_per_month": 500000,
  "storage_mb": 524288,
  "api_requests_per_month": 5000000,
  "phone_numbers": 50,
  "whatsapp_accounts": 25,
  "custom_fields": 2000,
  "reports": 1000,
  "exports_per_month": 20000,
  "messages_per_month": 500000,
  "agents": 100,
  "storage_gb": 512
}
$limits_21$::jsonb,
  72,
  false,
  false,
  true,
  false,
  'custom'
)
ON CONFLICT (code) DO UPDATE SET
  name=EXCLUDED.name,
  tier=EXCLUDED.tier,
  description=EXCLUDED.description,
  tagline=EXCLUDED.tagline,
  badge=EXCLUDED.badge,
  cta_label=EXCLUDED.cta_label,
  price_cents=EXCLUDED.price_cents,
  currency=EXCLUDED.currency,
  interval=EXCLUDED.interval,
  trial_days=EXCLUDED.trial_days,
  features=EXCLUDED.features,
  limits=EXCLUDED.limits,
  sort_order=EXCLUDED.sort_order,
  is_active=EXCLUDED.is_active,
  is_public=EXCLUDED.is_public,
  is_custom=EXCLUDED.is_custom,
  highlight=EXCLUDED.highlight,
  monthly_plan_code=EXCLUDED.monthly_plan_code;

-- 5. Visibility defaults
-- Public monthly: Free, Starter, Professional, Growth, Business, Enterprise.
-- Public yearly : Starter, Professional, Growth, Business.
-- Hidden        : all Lifetime, all Custom, Free Yearly/Lifetime,
--                 Enterprise Yearly/Lifetime.
--
-- Custom rows are intentionally inactive/private. Review price, limits,
-- features, commercial terms, then activate only for the intended customer.
-- End.
